#server:
#  port: 8111
#
#spring:
#  application:
#    name: dfe-wayline
#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB

spring:
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
